services:
  db:
    image: postgres:16-alpine
    container_name: trackmybooks-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: trackmybooksdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  book-service:
    build: ./backend/book-service
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

  frontend-web:
    build: ./frontend/track-my-books
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - book-service
volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge