"use client";

import { use, useState } from "react";
import {Navbar} from "@/_components/Navbar";
import { Footer } from "@/_components/Footer";
import { useSearchParams } from "next/navigation";
import Link from "next/link";

const PRIVACY_SECTIONS = [
  {
    title: "1. Data Controller",
    content: `Data Controller of your personal data is Track My Books sp. z o.o. with its registered office in Krakow, at 12/4 Literacka Street, 00-000 Krakow (hereinafter: "Track My Books").

In matters related to data protection, you can contact our Data Protection Officer at: dpo@trackmybooks.pl.`,
  },
  {
    title: "2. What Data We Collect",
    content: `Data provided by you: name and surname, pseudonym, email address, password (stored in hashed form).

Data generated by your use of the Service: reading history, ratings, reviews, reading lists, activity in the Service.

Technical Data: IP address, device identifier, browser type, operating system, timestamp.

We do not collect special categories of personal data (e.g., health data, religious beliefs, sexual orientation).`,
  },
  {
    title: "3. Purposes and Legal Basis for Processing",
    content: `Provision of Services (Article 6(1)(b) GDPR) – registration, login, account personalization, reading history.

Legitimate Interest of Track My Books (Article 6(1)(f) GDPR) – security, prevention of abuse, statistical analysis for improving the Service, recommendations.

User Consent (Article 6(1)(a) GDPR) – email marketing, analytical and marketing cookies.

Legal Obligation (Article 6(1)(c) GDPR) – storage of transactional data required by tax and accounting regulations.`,
  },
  {
    title: "4. Sharing of Data",
    content: `We share your data exclusively with trusted third-party providers (hosting: AWS, analytics: own EU servers) based on data processing agreements; public authorities when required by law; other users – solely publicly visible data on your profile.

We never sell your personal data.`,
  },
  {
    title: "5. Your Rights",
    content: `You have the right to: access your data and receive a copy; rectify inaccurate or incomplete data; delete your data (the "right to be forgotten"); restrict processing; port your data; object to processing based on legitimate interest; withdraw consent at any time (without affecting the lawfulness of processing prior to withdrawal); file a complaint with the President of the Office for Personal Data Protection.

To exercise these rights, please contact us at: privacy@trackmybooks.pl.`,
  },
  {
    title: "6. Data Retention",
    content: `Account data we store for the duration of the service agreement and for 3 years after its termination (statute of limitations).

Transactional data for 5 years (tax obligations).

Technical logs for 90 days.

You can delete your account at any time from the Settings, which will result in the deletion of your data except for those that we must retain due to legal obligations.`,
  },
];

const COOKIE_TYPES = [
  {
    name: "Essential",
    icon: "🔒",
    desc: "Required for the website to function. You cannot disable them.",
    examples: ["session_id", "csrf_token", "consent"],
    required: true,
  },
  {
    name: "Analytical",
    icon: "📊",
    desc: "Help us understand how you use the Service (own analytics, no Google Analytics).",
    examples: ["_bt_analytics", "_bt_session_start"],
    required: false,
  },
  {
    name: "Functional",
    icon: "⚙️",
    desc: "Remember your preferences (theme, language, sorting).",
    examples: ["_bt_prefs", "_bt_theme"],
    required: false,
  },
];

export default function PrivacyPage() {
  const searchParams = useSearchParams();
  const [tab, setTab] = useState<"privacy" | "cookies">(searchParams.get("tab") === "cookies" ? "cookies" : "privacy");
  if (searchParams.get("tab") != tab) {
    setTab(searchParams.get("tab") === "cookies" ? "cookies" : "privacy");
  }

  const [cookiePrefs, setCookiePrefs] = useState<Record<string, boolean>>({
    Analytical: true, Functional: true, Marketing: false,
  });

  return (
    <>
      <Navbar />
      <div className="inner-page legal-page">
        <div className="legal-header">
          <div className="page-eyebrow"><span className="eyebrow-line" />Legal Documents<span className="eyebrow-line" /></div>
          <h1 className="page-title">Privacy & Cookies</h1>
          <p className="page-subtitle">Last updated: March 1, 2026</p>
        </div>

        {/* Doc tab switcher */}
        <div className="legal-doc-tabs">
          <Link href="/privacy?tab=privacy" 
            className={`legal-doc-tab ${tab === "privacy" ? "active" : ""}`}
          >
            🔐 Privacy Policy
          </Link>
          <Link href="/privacy?tab=cookies" 
            className={`legal-doc-tab ${tab === "cookies" ? "active" : ""}`}
          >
            🍪 Cookie Policy
          </Link>
        </div>

        {/* PRIVACY */}
        {tab === "privacy" && (
          <div className="legal-layout">
            <aside className="legal-toc">
              <div className="legal-toc-title">Spis treści</div>
              <ul className="legal-toc-list">
                {PRIVACY_SECTIONS.map(s => (
                  <li key={s.title}><a href={`#${s.title}`} className="legal-toc-link">{s.title}</a></li>
                ))}
              </ul>
            </aside>
            <div className="legal-content">
              {PRIVACY_SECTIONS.map(s => (
                <section className="legal-section" key={s.title} id={s.title}>
                  <h2 className="legal-section-title">{s.title}</h2>
                  <div className="legal-body">
                    {s.content.split("\n\n").map((p, i) => <p key={i}>{p}</p>)}
                  </div>
                </section>
              ))}
              <div className="legal-footer-note">
                Questions about privacy? <strong>privacy@trackmybooks.pl</strong>
              </div>
            </div>
          </div>
        )}

        {/* COOKIES */}
        {tab === "cookies" && (
          <div className="cookies-layout">
            <div className="stats-card" style={{ padding: 28, marginBottom: 20 }}>
              <h3 className="stats-card-title">What are cookies?</h3>
              <p style={{ fontSize: 14, color: "var(--text-muted)", lineHeight: 1.7 }}>
                Cookies are small text files stored on your device by your browser.
                We use them to ensure the website functions properly, remember your preferences
                and help us improve it. Below you can manage your consent.
              </p>
            </div>

            <div className="cookies-cards">
              {COOKIE_TYPES.map(c => (
                <div className="cookie-card" key={c.name}>
                  <div className="cookie-card-top">
                    <div className="cookie-card-left">
                      <span className="cookie-icon">{c.icon}</span>
                      <div>
                        <div className="cookie-name">{c.name}</div>
                        <div className="cookie-desc">{c.desc}</div>
                      </div>
                    </div>
                  </div>
                  <div className="cookie-examples">
                    {c.examples.map(e => <code key={e} className="cookie-name-tag">{e}</code>)}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
      <Footer />
    </>
  );
}